### ISSUE TITLE
Deriver for [bundle]_type taxonomy

### ISSUE THREAD

**Issue by rlnorthcutt** [acquia/df#104]
We should have a deriver that automatically creates a [bundle]_type taxonomy and adds it as a field when the content type is created. Similarly, it should remove this taxonomy if the content type in question is deleted.

**Comment by saltednut** [comment]
I think its probably too heavy handed and would be a waste of time but I do appreciate you taking stuff that I dream up on calls and trying to turn them into action items. This one just isn't worth it though. Maybe we'll find an excuse to use derivers for something else someday.
