### ISSUE TITLE
Create person content type

### ISSUE THREAD

**Issue by rlnorthcutt** [acquia/df#106]
We need an event content type:

- Title (default node title, auto-generated from first/last, hidden field)
- First name (required)
- Last name (required)
- Greeting (select list - mr, ms, mrs, mx, dr)
- Job title
- Body
- Image (field_image)
- Contact information (text area with simple editor)
- person_type taxonomy reference
- tags taxonomy reference
- meta tag field

Need to have view modes based on location/article view modes.

**Comment by saltednut** [comment]
Added this content type with all the fields, needs view mode configuration and theme.
