### ISSUE TITLE
Focal point not working

### ISSUE THREAD

**Issue by rlnorthcutt** [acquia/df#110]
When I create media, and choose a focal point, it does not seem to respect the focal point for the crop.

Related: #111

**Comment by rlnorthcutt** [comment]
Might need to disable/remove manual crop and put it into its own optional demo module. Focal should be in by default, but manual crop should be an add on.

**Comment by saltednut** [comment]
Focal point works but its a bit tricky since we have default unsplash field values. You must first clear the unsplash field value then the widget will show up and you can set a focal point. I can work on the UX here to do something different than the show/hide?

**Comment by saltednut** [comment]
![image-manualcrop](https://user-images.githubusercontent.com/1102654/60841607-d6f49e80-a197-11e9-876a-ece6ca978455.gif)

**Comment by saltednut** [comment]
I'm going to close this as working but we can open another issue for the next milestone to help with the confusing ootb UX.
