### ISSUE TITLE
LB - content/media embed not working

### ISSUE THREAD

**Issue by rlnorthcutt** [acquia/df#113]
When trying to add a content/media embed block, it spins and no block is added. We need to fix this in the module, or find an alternative.

**Comment by kevinfunk** [comment]
I have found success embedding content/media using Entity Browser -> Browser for Content and Entity Browser -> Media browser. It's not intuitive, but it works.

**Comment by saltednut** [comment]
Is there a way we can make that flow more intuitive? I wonder if this issue blocks the alpha or if we should move it to the next milestone.

**Comment by saltednut** [comment]
I know it might seem weird but one thing that would simplify this is if we remove the `block_content.type.media` from df_tools_blocks - this would force people to embed content the other way.

**Comment by saltednut** [comment]
Ah okay nm I see whats going on here. So there's just way too many options on the sidebar and this is really in some ways a sub-issue of #114 . We need to file feedback issues detailing that this doesn't work, but in the meantime we should work out #114 and how we're going to handle it - my take is that we should look at following through with this: https://www.drupal.org/project/block_blacklist/issues/3055871

**Comment by kevinfunk** [comment]
Commit [b5cfefe](https://github.com/acquia/df/commit/b5cfefeb2108144103613e6e4a32432a7c29962a) fixes Content Embed and commit [f6e4796](https://github.com/acquia/df/commit/f6e47960cd2225f01ba306a9f0d7dad5166762d7) fixes Media Embed.
