### ISSUE TITLE
LB block list cleanup

### ISSUE THREAD

**Issue by rlnorthcutt** [acquia/df#114]
We need to audit the list of blocks that show up in the list of LB sidebar, and unset/remove the ones we don't need. Additionally, we should collapse all the sidebar fieldsets by default.

**Comment by saltednut** [comment]
See: https://www.drupal.org/project/block_blacklist/issues/3055871

I'm going to put together a block whitelist module since the maintainer here never got back to me and I hate blacklists.

**Comment by saltednut** [comment]
And I like the names "safe-list" verus white or black here since a) there's problematic signifiers in using black/white for things b) Safe implies that some things hidden are possibly broken, which is true.

**Comment by saltednut** [comment]
Its worth noting that https://www.drupal.org/project/layout_builder_restrictions exists as another option though I kind of want to control this on a more global scale. Will look into using it and issues with it first though.

**Comment by saltednut** [comment]
We will block this with #113

**Comment by saltednut** [comment]
re-added the embed blocks so we're good here on the "Landing Page" content type
