### ISSUE TITLE
Material admin default field text overlay

### ISSUE THREAD

**Issue by rlnorthcutt** [acquia/df#116]
When a field has a default value, the label text is overlaid. This should only be on empty fields. May also be related to the need to double click on select lists. Should be fixed and see about porting back to the theme.

**Comment by saltednut** [comment]
We should also look and see if this is possibly affecting the date popup. My suspicion is that the JS in material admin might need a rewrite in a few areas to make it less aggressive on fields etc.

**Comment by saltednut** [comment]
These were separate issues but both have been fixed as of https://github.com/acquia/df/commit/ecb42e91042ba1785803bcd2c12c5847b238afdd
