### ISSUE TITLE
LB - consider adding layout_builder_modal module

### ISSUE THREAD

**Issue by rlnorthcutt** [acquia/df#119]
https://www.drupal.org/project/layout_builder_modal

This looks like it would be an easy and nice UX upgrade. Worth investigating.

**Comment by saltednut** [comment]
This is in the codebase as of a month ago and last I checked it was turned on by default?

https://github.com/acquia/df/blame/e9647d8d251852436249b82c50f0ec284b58f05b/composer.json#L223

**Comment by saltednut** [comment]
It was added there by @kevinfunk and then also a dependency added to df_tools_blocks here: https://github.com/acquia/df/commit/3a58981bc77658d221fa57f6b70d6ed352c00e83
