### ISSUE TITLE
Fix card styles on mobile in ONE theme

### ISSUE THREAD

**Issue by saltednut** [acquia/df#127]
![Screenshot_20190712-081644](https://user-images.githubusercontent.com/1102654/61130948-845c0080-a47d-11e9-89cb-f43c5128831e.jpg)

**Comment by kevinfunk** [comment]
Fixed by adding a custom column class `col-12`,  commit [818abbe](https://github.com/acquia/df/commit/818abbe0b1f228514e175b36b62d09945da401a1).
