### ISSUE TITLE
One needs to Edit media from the "Grid" view

### ISSUE THREAD

**Issue by saltednut** [acquia/df#128]
It seems weird that one can click on media in the grid but can only perform bulk operations. Each Media item in the view should have an edit link, similar to the table view.
Shown: Media library grid in DF (Material Admin theme)
<img width="1332" alt="Screen Shot 2019-07-12 at 10 54 17 AM" src="https://user-images.githubusercontent.com/1102654/61141740-da3ba300-a493-11e9-8fa6-bbeb36dd7d34.png">
Shown: Table view has the "Edit" action.
<img width="1352" alt="Screen Shot 2019-07-12 at 10 53 18 AM" src="https://user-images.githubusercontent.com/1102654/61141743-dc9dfd00-a493-11e9-8576-86b72ea55d56.png">

**Comment by saltednut** [comment]
We'd prefer not to override the view if it is coming from Lightning or core. Seems like something everyone could use?

**Comment by saltednut** [comment]
<img width="964" alt="Screen Shot 2019-07-12 at 11 30 45 AM" src="https://user-images.githubusercontent.com/1102654/61143715-97c89500-a498-11e9-98b2-df5d463b0013.png">
Lightning also affected by this, so we should look at the media browser and see what we can do maybe.
@balsama do you have an opinion here? I can file a PF or w/e but maybe there's already plan already in place?

**Comment by balsama** [comment]
The ML view _should_ provide a link to the media entity edit page too. The top half/preview portion selects for bulk operations and the name below links to the entity edit page.

Maybe DFs theme is iterfering with that? Just speculating. You can test in Lightning's sandbox here: https://lightning.acquia.com/lightning (admin/admin)

Example gif:
![ml-link-2](https://user-images.githubusercontent.com/1536654/61152131-99ed1c80-a4b5-11e9-8c2f-6964691ef62e.gif)

**Comment by saltednut** [comment]
Thanks, @balsama - I see it now in my Lightning install.

You're right - it looks like DF is stripping the edit link.  We'll investigate and resolve on our end.

<img width="611" alt="Screen Shot 2019-07-12 at 4 29 37 PM" src="https://user-images.githubusercontent.com/1102654/61159674-5e0c8400-a4c2-11e9-9931-2b6081780d73.png">

**Comment by kevinfunk** [comment]
Our template is coming from Material Admin Support.
![image](https://user-images.githubusercontent.com/25224235/61163854-e0a33c80-a4de-11e9-80e1-d89941c44709.png)

**Comment by balsama** [comment]
Related, have you tried [Claro](https://www.drupal.org/project/claro) yet? They haven't gotten to the Media Library _yet_ but it's in their roadmap. https://www.drupal.org/project/claro/issues/3062751

**Comment by saltednut** [comment]
Yep we have started including it in our build (Claro) but its not turned on by default. Looks like Media and Views still need work. Its very vanilla looking to me but perhaps if someone adds color module integration it will be more appealing.

**Comment by saltednut** [comment]
This looks good as of 1308e95ad4da0095cbe495ce785fc674c8fd443b thanks @kevinfunk 
<img width="239" alt="Screen Shot 2019-07-15 at 4 34 31 PM" src="https://user-images.githubusercontent.com/1102654/61250903-98725d00-a71e-11e9-94dc-988425750eee.png">
