### ISSUE TITLE
Replace any existing Image fields on node bundles to use Media Image entity references

### ISSUE THREAD

**Issue by kevinfunk** [acquia/df#137]
Images should be added as a Media reference with a widget of Entity Browser. The Entity browser should be Media browser (Modal). Display Edit button, Display Remove button, and Show widget details as open by default should be selected. The selection mode should be Append to selection and the view mode should be Thubnail.
![image](https://user-images.githubusercontent.com/25224235/61877106-55518000-aebc-11e9-8d8d-6e30e3c4c323.png)
![image](https://user-images.githubusercontent.com/25224235/61877119-597d9d80-aebc-11e9-9d69-a6bfc381a7ec.png)

**Comment by saltednut** [comment]
> Images should be added as a Media reference with a widget of Entity Browser

Where?

**Comment by saltednut** [comment]
This needs a more specific title too. I am not sure what you're proposing here.

**Comment by rlnorthcutt** [comment]
I believe this is not necessarily about a specific field, but more about making this the new standard and making sure we have consistency. I altered the title to show that we need to "audit" the codebase to be sure all image fields are now media fields in our entities.

**Comment by saltednut** [comment]
So this is really just looking at the content types (node bundles) and determining if there are any image fields being used?  We don't have any other entity types that would use an image. You have to have an image field on the media (media:image bundle) so just searching the codebase for all image fields is not specific enough. I would prefer, rather than adding "audit" we have a real direction.

**Comment by kevinfunk** [comment]
Ron's correct, this was more about documentation.

**Comment by kevinfunk** [comment]
I've updated the Banner image to use a modal to provide a similar experience and I've put in a ticket for Lightning to change the Banner image to a media entity. Since everything we have control over uses a media image, I'm going to close this issue.
