### ISSUE TITLE
Modal popup theming

### ISSUE THREAD

**Issue by rlnorthcutt** [acquia/df#141]
The modal popups in LB and other places uses the default jQuery UI theming. We need to provide Radix override CSS that makes them look more modern and clean.

**Comment by rlnorthcutt** [comment]
Use OBIO as a guide. We also need to be sure that 
- modals block scrolling, 
- close when clicking outside the modal, 
- close when hitting the escape key, 
- take up more of the usable screen, 
- have some type of CSS animation (if possible), 
- and otherwise have more of an app-like feel.

**Comment by kevinfunk** [comment]
Commit [6e76e34](https://github.com/acquia/df/commit/6e76e34639f151fce111c8264dd1c81c097b18be) finishes the UI theming.
