### ISSUE TITLE
Hide revision log field when new content is created

### ISSUE THREAD

**Issue by rlnorthcutt** [acquia/df#144]
When new content is being created, there really isn't any need for the revision log field. We should hide it and set a default value like:
"Initial content creation by [username]"

This creates a cleaner, simpler form and will make the demo look less confusing.

**Comment by rlnorthcutt** [comment]
<img width="1621" alt="landingpage-before" src="https://user-images.githubusercontent.com/673633/61909877-d2024f80-aef8-11e9-990e-28499a898c17.png">
<img width="1612" alt="landingpage-after" src="https://user-images.githubusercontent.com/673633/61909879-d2024f80-aef8-11e9-8bcb-900697a9af01.png">

**Comment by rlnorthcutt** [comment]
This should be done for media as well. Can we do it at a high enough level that it works for all revision-able entities?

**Comment by rlnorthcutt** [comment]
This might be worth doing as a core issue/patch as well.

**Comment by saltednut** [comment]
I agree just setting this to something like "Originally created by [username] on [MM-DD-YYY]" would be sane and it'd take thinking out of the matter as that text box is competing with the other form elements while not providing much value on the initial `node/add` page.
