### ISSUE TITLE
Uncheck "show title" when placing blocks

### ISSUE THREAD

**Issue by rlnorthcutt** [acquia/df#145]
Most of the time when we place a block in the system or in LB, we need to uncheck the "show title" option. In my experience, I need it unchecked more often than I need it checked. 

Let's create a core issue and patch to change the default. This should be easy and should get included.

**Comment by saltednut** [comment]
Still working on this? I'd take a crack at it if you're not.

**Comment by saltednut** [comment]
Core patch filed. https://www.drupal.org/project/drupal/issues/3074435
