### ISSUE TITLE
JSONAPI explorer

### ISSUE THREAD

**Issue by rlnorthcutt** [acquia/df#146]
https://www.drupal.org/project/jsonapi_explorer

We should add this to the DF codebase, and create a df_tools module that enables and configures it (if needed). This module (created by Acquia) allows devs to easily build a custom JSONAPI request with filters and parameters by simply clicking buttons. It will show well for devs, and it will make it easier to do any custom development.

I've also created a PF ticket for Lightning.

**Comment by saltednut** [comment]
I've added this but its currently breaking the build because one of its dependencies adds a patch.

```
docroot/modules/contrib/jsonapi_schema/composer.json
28:                "3014277 - ResourceTypes should know about their fields": "https://www.drupal.org/files/issues/2019-06-06/3014277--resource-fields--36.patch"
```

**Comment by saltednut** [comment]
https://travis-ci.org/acquia/df/builds/565677711#L887

**Comment by saltednut** [comment]
b3029d27b8070afa35fd8f349bb6d1eea688c01e closes this
