### ISSUE TITLE
Replace drupal_set_message

### ISSUE THREAD

**Issue by rlnorthcutt** [acquia/df#154]
See http://hojtsy.hu/blog/2019-jul-30/prepare-drupal-9-stop-using-drupalsetmessage

Looks like we have this in 3 places in DF. We should replace it and use a new standard.

**Comment by saltednut** [comment]
This should be alright. We'll see who/what breaks when we get to D9 but at least the code we maintain is up to date.

**Comment by rlnorthcutt** [comment]
Awesome! There is also an updater tool that we can use in the future to scan the codebase. This will be good for making sure that we have one less thing to change, and it sets the "standard" for DF.
