### ISSUE TITLE
Add environment indicator module and config override

### ISSUE THREAD

**Issue by rlnorthcutt** [acquia/df#157]
We should add the environment indicator module for the demo. There is a config override that PS has that sets the variables and colors for you based on the Acquia environment detector added by BLT:
https://github.com/acquia-pso/oracle/blob/master/src/Config/OracleConfigOverrides.php

**Comment by saltednut** [comment]
I don't have access to that repo. We should be careful what we link to on this OSS project.

**Comment by saltednut** [comment]
We wont always have BLT and it sounds like we'll get that for free if we use Oracle at some point. I wonder if its not a good idea to duplicate their code, but instead try to bring it in somehow?

**Comment by saltednut** [comment]
Lets open a followup to figure out how to use their configs without duplicating efforts.
