### ISSUE TITLE
Unsplash id import fails on fresh install

### ISSUE THREAD

**Issue by rlnorthcutt** [acquia/df#191]
Working on 8.x-4.x with a "plain" install of DF. When I try to add image media using the Unsplash id, I get a validation form error: "Image field is required."

The image field is marked as "Required", and when I remove that, it works. Seems like we have some config rewrite/overwrite that is failing to apply.

**Comment by saltednut** [comment]
49c9122f31294059e9e36a52665e2566ca64c57c
