### ISSUE TITLE
Make Gradient optional on Hero Block provided by DF

### ISSUE THREAD

**Issue by saltednut** [acquia/df#194]
Related to the 8.x-4.x-404 branch.  I am not liking how we are using the gradient overlay on all the imagery. I looked into turning it off but it seems like it can't be done?  Unless there's something I am missing, it might make sense to add a boolean to turn off the gradient overlay on hero blocks.

**Comment by rlnorthcutt** [comment]
Beat me to it. I was gonna make a similar ticket! Can we also put the "theming" options for the hero in a collapsed fieldset?

**Comment by saltednut** [comment]
This works fine on my end!
