### ISSUE TITLE
Page manager pages in Default DF (one theme) should be full width

### ISSUE THREAD

**Issue by saltednut** [acquia/df#195]
Currently all page_manager content created has gutters on both sides that don't look very good for most of the stuff we're trying to build in dfs_default.  I tried adding `col-lg-12` class to the Hero block but it did not bleed outside the forced gutters.
<img width="1552" alt="Screen Shot 2019-12-11 at 6 40 49 PM" src="https://user-images.githubusercontent.com/1102654/70672737-c57f5900-1c45-11ea-939f-b65c588afe3e.png">

**Comment by rlnorthcutt** [comment]
df_tools_display has an existing landing page variant. Are we using this anywhere? Does it make sense to just alter this to work with Bootstrap OOTB?
