### ISSUE TITLE
Scenario chooser 500 error

### ISSUE THREAD

**Issue by rlnorthcutt** [acquia/df#202]
Bug report from Alan:

`Hey Ron

I get a server error when I try in install a scenario on this newly clones site

This site was cloned from the ACSF template folder

My ACSF sites > https://www.demoacsftest1.acsitefactory.com/sites-by-group/grid/5156

I've looked at the instructions here but can't see anything that would help here 

What am I doing wrong?

Cheers.

Alan`

**Comment by rlnorthcutt** [comment]
I checked it out with all 3 scenarios, and I get the same. The second you hit the "install demo" button on the scenario chooser, its a 500. I look and see this in watchdog:

"Drupal\Core\Extension\Exception\UnknownExtensionException: The module df_tools_menu does not exist. in Drupal\Core\Extension\ExtensionList->getPathname() (line 522 of /mnt/www/html/demoacsftest101live/docroot/core/lib/Drupal/Core/Extension/ExtensionList.php)."

Clearing cache does not help.

I can confirm that the "df_tools_menu" is not in the codebase, and doesn't seem to be in the DF or demo_framework codebases. Was removed here:
https://github.com/acquia/df/commit/2844e07e260a999d7186f16113d46bf17fe13cca

So, we need to figure out why this is happening and what is requiring it.

**Comment by saltednut** [comment]
This was likely being caused by an older DB on a cloned site.
