### ISSUE TITLE
Add a generic /api-demo to the codebase

### ISSUE THREAD

**Issue by saltednut** [acquia/df#212]
It can just show articles on the right and the JSON output on the left.

Similar to this kind of thing we added to the old demo.

<img width="1129" alt="Screen Shot 2020-03-06 at 1 36 06 PM" src="https://user-images.githubusercontent.com/1102654/76116455-a3c91000-5faf-11ea-8589-8d4e7b8c886f.png">

**Comment by saltednut** [comment]
We may actually wanna ship this with the article content type. And not make it part of DFS Default per say, but most scenarios would have it turned on.

**Comment by saltednut** [comment]
This is pretty far along, was easy to copy from a previous demo and modify it.  However, I am having issues getting the JS side of things working correctly and we need to theme the page to use two columns correctly.

**Comment by saltednut** [comment]
![Screen Shot 2020-03-06 at 5 39 44 PM](https://user-images.githubusercontent.com/1102654/76130738-7f7e2b00-5fd1-11ea-90de-9e85cec81fdc.png)
Current state

**Comment by saltednut** [comment]
![api-demo-2](https://user-images.githubusercontent.com/1102654/76131624-d89b8e00-5fd4-11ea-800b-1d02b40b00e0.gif)

**Comment by saltednut** [comment]
I think we can do better but this can work for the first take until @kevinfunk has time to come in and polish it up to use 2 columns and do more than just collapse. No rush, this current state should be good enough to do the demo, but having 2 cols would be better.

**Comment by kevinfunk** [comment]
![Screen Shot 2020-04-06 at 2 08 04 PM](https://user-images.githubusercontent.com/25224235/78593722-10386880-7815-11ea-85d7-e26b8717ad3c.png)

![Screen Shot 2020-04-06 at 2 08 36 PM](https://user-images.githubusercontent.com/25224235/78593729-13335900-7815-11ea-8edc-7218f27e0d37.png)
