### ISSUE TITLE
URL alias patterns need adjustment

### ISSUE THREAD

**Issue by rlnorthcutt** [acquia/df#215]
On a fresh install of DF, I have enabled the DF tools content types. I checked the URL patterns, and we need to adjust a few things

1) Without enabling translations, I get english, spanish, and french translation path patterns... but they don't know about languages yet. These should likely be optional config for the df_tools_translations module, right?

2) I think we should just make "english" the default, and no need to label it as such... just "Article" is fine for the default.

3) Suggestions - We should change the name of the translations to put the language last. This makes it a bit easier to organize, I think. All articles will be together.

4) The location path is referencing the "field_location_type", but that doesn't exist. Its just "field_type"

5) Suggestion - all content types should potentially have the "type" field in the path. Then we have a cleaner default structure OOTB.

6) Suggestion - we should make a "content type" taxonomy path that matches the language version. This way, we can have a logical structure with views for all paths (views can be in another ticket)
Example
 - /content = view of all articles (view included with df_tools_articles)
 - /content/blog = view of all articles with blog content type (variation of view above)
 - /content/blog/my-awesome-post = a specific blog page

<img width="1207" alt="url-alias-defaults" src="https://user-images.githubusercontent.com/673633/77008355-05846500-6934-11ea-8ca9-3b615cd7dfe5.png">

**Comment by rlnorthcutt** [comment]
Alternatively, we could remove the language variations of patterns to keep it simple. This will get way more complex when we have Japanese, German, etc.

**Comment by kevinfunk** [comment]
Article 
`/[node:content-type]/[node:field_type]/[node:created:custom:Y]/[node:created:custom:m]/[node:created:custom:d]/[node:title]`

Basic page
`/[node:field_type]/[node:title]`

Event
`/[node:content-type]/[node:field_type]/[node:created:custom:Y]/[node:created:custom:m]/[node:created:custom:d]/[node:title]`

Landing page
`[node:title]`

Location
`/[node:content-type]/[node:field_type]/[node:title]`

Person
`/[node:content-type]/[node:field_type]/[node:title]`

@rlnorthcutt do you have any changes or can we close this?

**Comment by rlnorthcutt** [comment]
A few minor changes:
1) For the label, lets prefix the entity type. This keeps things grouped logically:
     - Content - article
     - Content - event
     - Content - page
2) I think we should replace the `[node:content-type]` with the actual name of the type. This makes it less confusing. IF we could bundle these then it would make sense to use the tokens (like location and person are the same), but we do want them to be separate. Example:
     - `/location/[node:field_type]/[node:title]`
     - `/person/[node:field_type]/[node:title]`
 3) For the date paths (event and article), lets use the 3 character month name and day without a leading zero. That will give a slightly friendlier url _(like \article\blog\2020\apr\6\my-title-here)_
    - `\article/[node:field_type]/[node:created:custom:Y]/[node:created:custom:M]/[node:created:custom:j]/[node:title]`
